language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t skrillybrick/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true skrillybrick/docker-react npm run test